accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('profile', views.ProfileView.as_view(), name='profile'),

    path('activate/<uidb64>/<token>', views.activate_profile, name='registration_activation'),

]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_cart'),
    path('remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='remove_cart'),
    path('update_cart/<int:cart_id>/<str:action>/<int:quantity>', views.UpdateCartItemQuantityView.as_view(),
         name='update_cart'),
]

eStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from eStore import views

app_name = 'eStore'
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HomeView.as_view(), name='home'),
                  path('store/', include('store.urls')),
                  path('cart/', include('carts.urls')),
                  path('accounts/', include('accounts.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have an username")
        if not first_name:
            raise ValueError("Users must have an first name")
        if not last_name:
            raise ValueError("Users must have an last name")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    phone = models.CharField(max_length=50)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'  # FORCE LOGIN WITH EMAIL
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    # class Meta:
    #     db_table = 'Account'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from accounts.models import Account


class RegistrationForm(forms.ModelForm):
    # add form-control class to all fields
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'password':
                self.fields[field].widget = forms.PasswordInput()
            self.fields[field].widget.attrs['class'] = 'form-control'

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'username', 'email', 'phone', 'password']

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Account.objects.filter(email=email)
        if r.count():
            raise forms.ValidationError("Email already exists")
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        r = Account.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return password

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

from django.shortcuts import render, redirect
# import generic views
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

# import models
from accounts.models import Account

from accounts.forms import RegistrationForm
from django.contrib import messages

# import login and authentication
from django.contrib.auth import authenticate, login, logout


# email stuff
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator


class RegisterView(CreateView):

    model = Account
    form_class = RegistrationForm
    template_name = 'accounts/register.html'
    # fields = ['first_name', 'last_name', 'username', 'email', 'password']
    success_url = '/accounts/login'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            password = form.cleaned_data['password']
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email,
                                         password=password)
            user.phone = phone
            user.save()

            # Email verification
            current_site = get_current_site(self.request)
            mail_subject = 'eStore | Verify your account.'
            message = render_to_string('accounts/acc_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'site_name': 'eStore',
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(self.request, 'Account created successfully. Please check your email for verification link.')
            return redirect('/accounts/login?command=verification&email=' + email)


            # return self.form_valid(form)
        else:
            return self.form_invalid(form)
    #
    def form_valid(self, form):
        form.instance.set_password(form.cleaned_data['password'])
        # form.save()
        messages.success(self.request, 'Account created successfully')
        return super().form_valid(form)


class LoginView(TemplateView):
    template_name = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('store:store')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None and user.is_active:
            login(request, user)
            # messages.success(request, 'Logged in successfully')
            return redirect('store:store')
        else:
            messages.error(request, 'Username or password is incorrect')
            return redirect('accounts:login')




class LogoutView(TemplateView,LoginRequiredMixin):
    # template_name = 'accounts/login.html'
    # @login_required(login_url='accounts:login')
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, 'You have been logged out successfully')
        return redirect('accounts:login')


class ProfileView(DetailView):
    model = Account
    template_name = 'accounts/signin.html'
    slug_field = 'username'


def activate_profile(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        messages.success(request, 'Your account has been activated successfully')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:register')

templates/accounts/acc_activation_email.html
{% autoescape off %}
    Dear {{ user.first_name }},

    You recently created an account on {{ site_name }}. To activate your account, click this link or copy and paste it into your browser:

    http://{{ domain }}{% url 'accounts:registration_activation' uidb64=uid token=token %}

    Thanks for joining {{ site_name }}!

    If you did not create an account, please ignore this email.(The link will expire in 48 hours and the profile will be deleted.)

    The {{ site_name }} team



{% endautoescape %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% if request.GET.command == 'verification' %}

        <div class="container mx-auto alert alert-info text-center" role="alert">

            Thank you for registering with us. Please check your email {{ request.GET.email }} for verification link.

            <br><br>
            Already Verified? <a href="{% url 'accounts:login' %}" class="">Login</a>

        </div>

    {% else %}
        <!-- ========================= SECTION CONTENT ========================= -->
        <section class="section-content padding-y" style="min-height:84vh">



        <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            <div class="card-body">


                <h4 class="card-title mb-4">Sign in</h4>
                {% include 'includes/alerts.html' %}

                <form action="{% url 'accounts:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address" name="email">
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Password" name="password">
                    </div> <!-- form-group// -->

                    <div class="form-group">
                        <a href="{% url 'accounts:login' %}" class="float-right">Forgot password?</a>

                    </div> <!-- form-group form-check .// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login</button>
                    </div> <!-- form-group// -->
                </form>
            </div> <!-- card-body.// -->
        </div> <!-- card .// -->

        <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
        <br><br>
        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}

</section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">

        <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            <article class="card-body">
                <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
                {% include 'includes/alerts.html' %}

                <form action="{% url 'accounts:register' %}" method="POST">
                    {% csrf_token %}

                    {#                    {% for field in form %}#}
                    {#                        <div class="fieldWrapper">#}
                    {#                            {{ field.errors }}#}
                    {#                            {{ field.label_tag }} {{ field }}#}
                    {#                            {% if field.help_text %}#}
                    {#                                <p class="help">{{ field.help_text|safe }}</p>#}
                    {#                            {% endif %}#}
                    {#                        </div>#}
                    {#                    {% endfor %}#}
                    {{ form.as_p }}
                    {#                    <div class="form-row">#}
                    {#                        <div class="col form-group">#}
                    {#                            <label>First name</label>#}
                    {#                            <input type="text" class="form-control" placeholder="">#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                        <div class="col form-group">#}
                    {#                            <label>Last name</label>#}
                    {#                            <input type="text" class="form-control" placeholder="">#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                    </div> <!-- form-row end.// -->#}
                    {#                    <div class="form-group">#}
                    {#                        <label>Email</label>#}
                    {#                        <input type="email" class="form-control" placeholder="">#}
                    {#                        <small class="form-text text-muted">We'll never share your email with anyone else.</small>#}
                    {#                    </div> <!-- form-group end.// -->#}
                    {#                    <div class="form-group">#}
                    {#                        <label class="custom-control custom-radio custom-control-inline">#}
                    {#                            <input class="custom-control-input" checked="" type="radio" name="gender" value="option1">#}
                    {#                            <span class="custom-control-label"> Male </span>#}
                    {#                        </label>#}
                    {#                        <label class="custom-control custom-radio custom-control-inline">#}
                    {#                            <input class="custom-control-input" type="radio" name="gender" value="option2">#}
                    {#                            <span class="custom-control-label"> Female </span>#}
                    {#                        </label>#}
                    {#                    </div> <!-- form-group end.// -->#}
                    {#                    <div class="form-row">#}
                    {#                        <div class="form-group col-md-6">#}
                    {#                            <label>City</label>#}
                    {#                            <input type="text" class="form-control">#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                        <div class="form-group col-md-6">#}
                    {#                            <label>Country</label>#}
                    {#                            <select id="inputState" class="form-control">#}
                    {#                                <option> Choose...</option>#}
                    {#                                <option>Uzbekistan</option>#}
                    {#                                <option>Russia</option>#}
                    {#                                <option selected="">United States</option>#}
                    {#                                <option>India</option>#}
                    {#                                <option>Afganistan</option>#}
                    {#                            </select>#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                    </div> <!-- form-row.// -->#}
                    {#                    <div class="form-row">#}
                    {#                        <div class="form-group col-md-6">#}
                    {#                            <label>Create password</label>#}
                    {#                            <input class="form-control" type="password">#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                        <div class="form-group col-md-6">#}
                    {#                            <label>Repeat password</label>#}
                    {#                            <input class="form-control" type="password">#}
                    {#                        </div> <!-- form-group end.// -->#}
                    {#                    </div>#}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register</button>
                    </div> <!-- form-group// -->

                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
        <br><br>
        <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}