carts/urls.py
from django.urls import path
from carts import views

app_name = 'carts'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_cart'),
    path('remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='remove_cart'),
    path('update_cart/<int:cart_id>/<str:action>/<int:quantity>', views.UpdateCartItemQuantityView.as_view(),
         name='update_cart'),
]

eStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from eStore import views

app_name = 'eStore'
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.HomeView.as_view(), name='home'),
                  path('store/', include('store.urls')),
                  path('cart/', include('carts.urls')),
                  path('accounts/', include('accounts.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from store import views

app_name = 'store'

urlpatterns = [
    path('', views.StoreListView.as_view(), name='store'),
    path('category/<slug:slug>/', views.StoreListView.as_view(), name='products_by_category'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchStoreListView.as_view(), name='search_results'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def __str__(self):
        return self.product.product_name

    def sub_total(self):
        return self.product.price * self.quantity

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=255, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    # image_url = models.CharField(max_length=2083)
    image = models.ImageField(upload_to='photos/products/', blank=True)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    # class Meta:
    #     db_table = 'Product'

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('store:product_detail', args=[self.slug])


variation_category_choice = [
    ('color', 'color'),
    ('size', 'size'),
]


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=255, choices=variation_category_choice)
    variation_value = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.product.product_name + ' - ' + self.variation_category + " --> " + self.variation_value

    def get_url(self):
        return reverse('store:product_detail', args=[self.product.slug])

carts/views.py
import decimal

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django.views import View

from carts.models import Cart, CartItem
from store.models import Product, Variation
from category.models import Category

from eStore.utils import _get_cart_id


class CartView(TemplateView):
    model = Cart
    template_name = 'store/cart.html'
    fields = ['quantity']
    context_object_name = 'cart'
    tax = decimal.Decimal(0.02)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            cart = Cart.objects.get(cart_id=_get_cart_id(self.request))
            all_items = CartItem.objects.filter(is_active=True, cart=cart)
            context['cart_items'] = all_items
            context['total_price_before_tax'] = round(sum(item.sub_total() for item in all_items), 2)
            context['total_tax'] = round(sum(item.sub_total() * self.tax for item in all_items), 2)
            context['total_price_after_tax'] = context['total_price_before_tax'] + context['total_tax']
            context['cart_size'] = all_items.count()
        except ObjectDoesNotExist:
            pass
        return context


# class AddToCartView(TemplateView):
#     model = Cart
#     template_name = 'store/cart.html'
#     fields = ['quantity']
#
#     def get(self, request, *args, **kwargs):
#         product_id = self.kwargs.get('product_id')
#         product = Product.objects.get(id=product_id)
#         try:
#             cart = Cart.objects.get(cart_id=self._get_cart_id(request))
#         except Cart.DoesNotExist:
#             cart = Cart.objects.create(
#                 cart_id=self._get_cart_id(request)
#             )
#             cart.save()
#
#         try:
#             cart_item = CartItem.objects.get(product=product, cart=cart)
#             if cart_item.quantity < cart_item.product.stock:
#                 cart_item.quantity += 1
#             cart_item.save()
#         except CartItem.DoesNotExist:
#             cart_item = CartItem.objects.create(
#                 product=product,
#                 quantity=1,
#                 cart=cart
#             )
#             cart_item.save()
#
#         return super().get(request, *args, **kwargs)
#
#     def get_redirect_url(self):
#         return redirect('carts:cart_detail')
#
#     # def get_context_data(self, **kwargs):
#     #     context = super().get_context_data(**kwargs)
#     #     context['products'] = self.products
#     #     return context
#
#     def _get_cart_id(self, request):
#         cart = request.session.session_key
#         if not cart:
#             cart = request.session.create()
#         return cart
#


class AddToCartView(TemplateView):
    # model = Cart

    def get(self, request, *args, **kwargs):
        product_id = kwargs.get('product_id')
        color = request.GET.get('color')
        size = request.GET.get('size')
        product = Product.objects.get(id=product_id)
        try:
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_get_cart_id(request)
            )
            cart.save()

        try:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            if cart_item.quantity < cart_item.product.stock:
                cart_item.quantity += 1
            cart_item.save()
        except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            cart_item.save()

        return redirect('carts:cart_detail')

    def post(self, request, *args, **kwargs):

        product_id = kwargs.get('product_id')
        product = Product.objects.get(id=product_id)

        product_variations = []
        for key in request.POST:
            value = request.POST[key]
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                  variation_value__iexact=value)
                product_variations.append(variation)
            except:
                pass

        try:
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_get_cart_id(request)
            )
            cart.save()
        cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

        # we have two choices here, either we can update the quantity of the cart item or we can create a new cart item
        update_quantity = False
        cart_item_id = None
        if cart_item_exists:  # if product exists in cart
            for curr_cart_item in CartItem.objects.filter(product=product, cart=cart):
                curr_item_variations = list(curr_cart_item.variation.all())
                if curr_item_variations == product_variations:
                    update_quantity = True
                    cart_item_id = curr_cart_item.id
                    break

        else:
            update_quantity = True

        if update_quantity:
            # update the quantity of the cart item which has the same product variation
            cart_item = CartItem.objects.get(product=product, id=cart_item_id)

            cart_item.quantity += 1
            cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )

            cart_item.variation.add(*product_variations)
            cart_item.save()

        return redirect('carts:cart_detail')


class RemoveFromCartView(TemplateView):

    def get(self, request, *args, **kwargs):
        product_id = kwargs.get('product_id')
        breakpoint()

        product = Product.objects.get(id=product_id)
        try:
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_get_cart_id(request)
            )
            cart.save()

        try:
            cart_item = CartItem.objects.get(product=product, cart=cart)
            cart_item.delete()
        except CartItem.DoesNotExist:
            pass

        return redirect('carts:cart_detail')


class UpdateCartItemQuantityView(TemplateView):
    def get(self, request, *args, **kwargs):
        cart_id = kwargs.get('cart_id')
        action = kwargs.get('action', 'add')
        quantity = kwargs.get('quantity', 1)
        # product = get_object_or_404(Product, id=product_id)

        try:  # TODO
            cart = Cart.objects.get(cart_id=_get_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_get_cart_id(request)
            )
            cart.save()
        try:
            cart_item = CartItem.objects.get(id=cart_id, cart=cart)
            if cart_item.quantity >= 1 and action == 'remove' and cart_item.quantity <= quantity:
                cart_item.delete()

            elif cart_item.quantity >= 1 and action == 'remove' and cart_item.quantity > quantity:
                cart_item.quantity -= quantity
                cart_item.save()

            elif action == 'add':
                total_addable = cart_item.product.stock - cart_item.quantity
                if total_addable > quantity:
                    cart_item.quantity += quantity
                else:
                    cart_item.quantity += total_addable

                cart_item.save()
        except CartItem.DoesNotExist:
            pass

        return redirect('carts:cart_detail')

store/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from store.models import Product
from category.models import Category
from carts.models import CartItem, Cart
from eStore.utils import _get_cart_id
from django.core.paginator import Paginator
from django.db.models import Q


class StoreListView(ListView):
    paginate_by = 5
    model = Product
    template_name = 'store/store.html'
    products = Product.objects.all().filter(is_available=True)

    # all_categories = Category.objects.all()

    def get(self, request, *args, **kwargs):
        category_slug = self.kwargs.get('slug')
        if category_slug:
            categories = get_object_or_404(Category, slug=category_slug)
            self.products = self.products.filter(category=categories)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.products = self.products.order_by('-id')
        products = Paginator(self.products, self.paginate_by)
        product_count = self.products.count()
        page = self.request.GET.get('page', 1)
        context['products'] = products.get_page(page)
        context['page_ob'] = products.get_page(page)
        context['product_count'] = product_count
        # context['categories'] = self.all_categories
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    # context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        in_cart = CartItem.objects.filter(cart__cart_id=_get_cart_id(self.request), product=product).exists()
        context['in_cart'] = in_cart
        return context


class SearchStoreListView(ListView):
    paginate_by = 5
    model = Product
    template_name = 'store/store.html'
    products = Product.objects.all().filter(is_available=True)

    # all_categories = Category.objects.all()

    def get(self, request, *args, **kwargs):
        category_slug = self.kwargs.get('slug')
        if category_slug:
            categories = get_object_or_404(Category, slug=category_slug)
            self.products = self.products.filter(category=categories)

        # handle search
        query = request.GET.get('q')
        if query:
            self.products = self.products.filter(Q(product_name__icontains=query) | Q(description__icontains=query))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.products = self.products.order_by('-id')
        products = Paginator(self.products, self.paginate_by)
        product_count = self.products.count()
        page = self.request.GET.get('page', 1)
        context['products'] = products.get_page(page)
        context['page_ob'] = products.get_page(page)
        context['product_count'] = product_count
        # context['categories'] = self.all_categories
        return context

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="section-content padding-y bg">
        <div class="container">
            {% if cart_size != 0 %}
                <h5 class="cart-title">
                    {{ cart_size }} items on cart
                </h5>
                <!-- ============================ COMPONENT 1 ================================= -->

                <div class="row">
                    <aside class="col-lg-9">
                        <div class="card">


                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                    <th scope="col" class="text-right" width="200"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ cart_item.product.image.url }}"
                                                                        class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="{{ cart_item.product.get_url }}"
                                                       class="title text-dark">{{ cart_item.product }}</a>

                                                    <p class="text-muted small">
                                                        {% for variation in cart_item.variation.all %}
                                                            {{ variation.variation_category | title }}:
                                                            {{ variation.variation_value |title }} <br>
                                                        {% endfor %}

                                                        Category: {{ cart_item.product.category }}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <!-- col.// -->
                                            <div class="col">
                                                <div class="input-group input-spinner">
                                                    <div class="input-group-prepend">
                                                        <a href="{% url 'carts:update_cart' cart_id=cart_item.id action='remove' quantity=1 %}">
                                                            <button class="btn btn-light" type="button"
                                                                    id="button-plus"><i
                                                                    class="fa fa-minus"></i></button>
                                                        </a>
                                                    </div>
                                                    <input type="text" class="form-control"
                                                           value="{{ cart_item.quantity }}">
                                                    <div class="input-group-append">
                                                        <a href="{% url 'carts:update_cart' cart_id=cart_item.id action='add' quantity=1 %}">
                                                            <button class="btn btn-light" type="button"
                                                                    id="button-minus"><i
                                                                    class="fa fa-plus"></i></button>
                                                        </a>

                                                    </div>
                                                </div> <!-- input-group.// -->
                                            </div> <!-- col.// -->
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">{{ cart_item.sub_total }}</var>
                                                <small class="text-muted"> ${{ cart_item.product.price }} each </small>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <a href="{% url 'carts:update_cart' cart_id=cart_item.id action='remove' quantity=cart_item.quantity %}"
                                               onclick="return confirm('Are you sure you want to remove the product from Cart?')"
                                               class="btn btn-danger"> Remove</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->
                    <aside class="col-lg-3">

                        <div class="card">
                            <div class="card-body">
                                <dl class="dlist-align">
                                    <dt>Price:</dt>
                                    <dd class="text-right">${{ total_price_before_tax }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Tax:</dt>
                                    <dd class="text-right"> ${{ total_tax }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Total Price:</dt>
                                    <dd class="text-right text-dark b"><strong>${{ total_price_after_tax }}</strong>
                                    </dd>
                                </dl>
                                <hr>
                                <p class="text-center mb-3">
                                    <img src="{% static './images/misc/payments.png' %}" height="26">
                                </p>
                                <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                            </div> <!-- card-body.// -->
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->


                </div> <!-- row.// -->
                <!-- ============================ COMPONENT 1 END .// ================================= -->
            {% else %}
                <h5 class="cart-title">
                    Your Shopping Cart is Empty
                </h5>
                <br>
                <div class="text-center">
                    <a class="btn btn-primary" href="{% url 'store:store' %}">Continue Shopping</a>
                </div>
            {% endif %}


        </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}



    <section class="section-content padding-y bg">

        <form action="{% url 'carts:add_cart' product.id %}" method="POST">
            {% csrf_token %}
            <div class="container">

                <!-- ============================ COMPONENT 1 ================================= -->
                <div class="card">
                    <div class="row no-gutters">
                        <aside class="col-md-6">
                            <article class="gallery-wrap">
                                <div class="img-big-wrap">
                                    <a href="#"><img src="{{ product.image.url }}"></a>
                                </div> <!-- img-big-wrap.// -->

                            </article> <!-- gallery-wrap .end// -->
                        </aside>
                        <main class="col-md-6 border-left">
                            <article class="content-body">

                                <h2 class="title">{{ product.product_name }}</h2>

                                <div class="mb-3">
                                    <var class="price h4">${{ product.price }}</var>
                                </div>

                                <p>{{ product.description }}</p>


                                <hr>
                                <div class="row">
                                    <div class="item-option-select">
                                        <h6>Select Color</h6>
                                        <select name="color" id="" class="form-control" required>
                                            <option value="" disabled selected>Select Color</option>
                                            {% for variation in product.variation_set.colors %}
                                                <option value="{{ variation.variation_value |lower }}">{{ variation.variation_value |capfirst }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div> <!-- row.// -->
                                <div class="row">
                                    <div class="item-option-select">
                                        <h6>Select Size</h6>
                                        <select name="size" id="" class="form-control" required>
                                            <option value="" disabled selected>Select Size</option>
                                            {% for variation in product.variation_set.sizes %}
                                                <option value="{{ variation.variation_value |lower }}">{{ variation.variation_value |capfirst }}</option>
                                            {% endfor %}

                                        </select>
                                    </div>
                                </div> <!-- row.// -->
                                <hr>
                                {% if product.stock > 0 and product.is_available %}
                                    {#                                    {% if in_cart == True %}#}
                                    {#                                        <a href="#" class="btn  btn-success disabled"> Added to cart <i#}
                                    {#                                                class="fas fa-check"></i>#}
                                    {#                                        </a>#}
                                    {#                                        <a href="{% url 'carts:cart_detail' %}" class="btn  btn-outline-primary">View#}
                                    {#                                            Cart <i class="fas fa-eye"></i> </a>#}
                                    {#                                    {% else %}#}
                                    <button type="submit" class="btn  btn-primary">
                                        <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>
                                    </button>
                                    {#                                    {% endif %}#}
                                {% else %}
                                    <a href="./product-detail.html" class="btn  btn-danger disabled"> <span
                                            class="text">Out of Stock</span> <i class="fas fa-shopping-cart"></i> </a>
                                {% endif %}
                            </article> <!-- product-info-aside .// -->
                        </main> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- card.// -->
                <!-- ============================ COMPONENT 1 END .// ================================= -->

                <br>

                <div class="row">
                    <div class="col-md-9">

                        <header class="section-heading">
                            <h3>Customer Reviews </h3>

                        </header>

                        <article class="box mb-3">
                            <div class="icontext w-100">
                                <img src="{% static './images/avatars/avatar1.jpg' %}"
                                     class="img-xs icon rounded-circle">
                                <div class="text">
                                    <span class="date text-muted float-md-right">24.04.2020 </span>
                                    <h6 class="mb-1">Mike John </h6>

                                </div>
                            </div> <!-- icontext.// -->
                            <div class="mt-3">
                                <p>
                                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                                    eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                                </p>
                            </div>
                        </article>


                    </div> <!-- col.// -->
                </div> <!-- row.// -->


            </div> <!-- container .//  -->


        </form>

    </section>


{% endblock %}